apiVersion: v1
kind: Service
metadata:
  name: demohttp-frontend
  labels:
    app: demohttp-frontend
spec:
  ports:
    - port: 8080
      name: demohttp-frontend
  selector:
    app: demohttp-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demohttp-frontend
  labels:
    app: demohttp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demohttp-frontend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: demohttp-frontend
    spec:
      containers:
        - name: demohttp-frontend
          image: pablosangueza/demohttp-frontend:flux-sync-3-gd84c559-dirty
          args:
            - "-addr=:8080"
            - "-backend-addr=http://demohttp-backend:8080"
          ports:
          - name: http
            containerPort: 8080
